### ISSUE TITLE
gnome-keyring-query compatability

### ISSUE THREAD

**Issue by cwmilwaukee** [tfl/muttvcardsearch#7]
Is there any way to allow for using gnome-keyring-query inside of muttvcardsearch?  Gkq is written in C but maybe there is a way to allow users to execute a shell command to add the option?  A description of gkq is available at the link below.  Thanks either way.  Muttvcardsearch is a great addition for mutt.

http://www.gentoo-wiki.info/HOWTO_Use_gnome-keyring_to_store_SSH_passphrases

**Comment by tfl** [comment]
Thanks for your comment. Now, I have to say that I am no longer work on muttvcardsearch. Well, I fixed some major bugs, yes. But I do not use Linux/UNIX anymore since I turned to photography in early 2014. So no, sorry, I do not even know what "gnome-keyring-query" is.
